version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  onboarding-client:
    build:
      context: .
      dockerfile: Dockerfile.onboarding-client.dev
      args:
        - NODE_ENV=development
    ports:
      - 4200:4200
    volumes:
      - type: bind
        source: .
        target: /src
      - /src/node_modules
    working_dir: /src

  onboarding-api:
    build:
      context: .
      dockerfile: Dockerfile.onboarding.dev
      args:
        - NODE_ENV=development
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=postgres
      - CHROMIUM_PATH=/usr/bin/chromium-browser
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - SALT_SECRET=${SALT_SECRET}
      - API_URL=${API_URL}
      - EMAIL_HOST=${EMAIL_PORT}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}

    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /src
      - /src/node_modules
    working_dir: /src
    depends_on:
      - postgres
