FROM node:16.8.0-alpine as production
WORKDIR /src
RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
ENV NODE_ENV=development
ENV SKIP_BUILD=1
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build:onboarding-api && npm run build:client:prod   
CMD ["node", "dist/apps/onboarding-api/main.js"]