version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  onboarding-client:
    build:
      context: .
      dockerfile: Dockerfile.onboarding-client.dev
      args:
        - NODE_ENV=development
    ports:
      - 4200:4200
    volumes:
      - type: bind
        source: .
        target: /src
      - /src/node_modules
    working_dir: /src
    environment:
      - API_URL=http://localhost:4200/

  onboarding-api:
    build:
      context: .
      dockerfile: Dockerfile.onboarding.dev
      args:
        - NODE_ENV=development
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - CHROMIUM_PATH=/usr/bin/chromium-browser
      - JWT_ACCESS_SECRET=test
      - JWT_REFRESH_SECRET=test2
      - SALT_SECRET=10
      - API_URL=http://localhost:4200/
      - EMAIL_HOST=smtp.ethereal.email
      - EMAIL_PORT=587
      - EMAIL_USERNAME=elyse.labadie91@ethereal.email
      - EMAIL_PASSWORD=rhumFETENbQSqERnEp
      - EMAIL_ADDRESS=elyse.labadie91@ethereal.email

    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /src
      - /src/node_modules
    working_dir: /src
    depends_on:
      - postgres
