
FROM node:16.8.0-alpine
ENV NODE_ENV=development

WORKDIR /src
COPY . .
RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/
RUN apk add chromium
RUN npm install
CMD npm run start:onboarding-api

